CREATE DATABASE burgers_db;
USE burgers_db;
CREATE TABLE Burgers (
id INT AUTO_INCREMENT NOT NULL,
burger_name VARCHAR(255),
devoured BOOLEAN,
createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(id));